@echo off
title Archangel Full Stack App
echo Starting Archangel Full Stack App (Google AI Studio UI)...
echo Launching Python Backend...
start cmd /k "cd C:\Users\adam\ark-omega && pip install fastapi uvicorn cors && uvicorn server:app --reload --port 8000"
echo Launching React Frontend...
start cmd /k "cd C:\Users\adam\ark-omega && npm run dev"
